openapi: '3.0.0'
info:
  version: 3.0.0
  title: Swagger Petstore
  description: This is a sample server Petstore server.
  license:
    name: MIT
externalDocs:
  url: http://swagger.io
  description: Find out more about Swagger
tags:
  - name: Pets
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      x-eventcatalog-message-type: query # This is a query operation
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}/adopted:
    post:
      summary: Notify that a pet has been adopted
      operationId: petAdopted
      tags:
        - pets
      x-eventcatalog-message-type: event # This is an event operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Adoption'
        required: true
      responses:
        '200':
          description: Notification that the pet has been adopted successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Adoption:
      type: object
      required:
        - petId
        - adopterName
      properties:
        petId:
          type: integer
          format: int64
        adopterName:
          type: string
          description: Name of the person who adopted the pet
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
